version: '3.8'

services:
  flask-api:
    build: ./api
    image: ${ECR_REPOSITORY}/flask-api:latest
    ports:
      - "5000:5000"
    volumes:
      - db-data:/app/store/

  websocket:
    build: ./websocket
    image: ${ECR_REPOSITORY}/websocket:latest
    ports:
      - "3001:3001"

  nextjs-server:
    build:
      context: ./web
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL:-localhost}
    image: ${ECR_REPOSITORY}/nextjs-server:latest
    ports:
      - "80:3000"

volumes:
  db-data:
